// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokMultilink, StoryblokRichtext, StoryblokTable } from '../storyblok.d.ts';
export interface StoryblokBanner {
  headline?: string;
  subheading?: string;
  backgroundImage?: StoryblokAsset;
  component: "banner";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokDropdown {
  component: "Dropdown";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokTest {
  component: "Test";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokButton {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  text?: string;
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokButtonAmadeu {
  label?: string;
  website?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "button_amadeu";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokDatePicker {
  label?: string;
  month_placeholder?: string;
  day_placeholder?: string;
  year_placeholder?: string;
  component: "date_picker";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokEmailInput {
  label?: string;
  suffix?: string;
  component: "email_input";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokFooter {
  companyName?: string;
  byline?: string;
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokHero {
  hero_image?: StoryblokAsset;
  hero_title?: string;
  hero_subtitle?: string;
  component: "hero";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokNavbar {
  logo?: StoryblokAsset;
  component: "navbar";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokNumberInput {
  label: string;
  suffix?: string;
  component: "number_input";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokPageTestAmadeu {
  teste1: string;
  teste2?: StoryblokTable;
  teste3?: {
    [k: string]: unknown;
  }[];
  custom_block?: (
    | StoryblokBanner
    | StoryblokDropdown
    | StoryblokTest
    | StoryblokButton
    | StoryblokButtonAmadeu
    | StoryblokDatePicker
    | StoryblokEmailInput
    | StoryblokFooter
    | StoryblokHero
    | StoryblokNavbar
    | StoryblokNumberInput
    | StoryblokPageTestAmadeu
    | StoryblokPage
    | StoryblokQuizPageType1
    | StoryblokSimplePage
    | StoryblokTestimonial
    | StoryblokTestimonialSection
    | StoryblokText
  )[];
  component: "page-test-amadeu";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokPage {
  navbar?: ISbStoryData<StoryblokNavbar> | string;
  body?: unknown[];
  footer: ISbStoryData<StoryblokFooter> | string;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokQuizPageType1 {
  body?: (
    | StoryblokBanner
    | StoryblokDropdown
    | StoryblokTest
    | StoryblokButton
    | StoryblokButtonAmadeu
    | StoryblokDatePicker
    | StoryblokEmailInput
    | StoryblokFooter
    | StoryblokHero
    | StoryblokNavbar
    | StoryblokNumberInput
    | StoryblokPageTestAmadeu
    | StoryblokPage
    | StoryblokQuizPageType1
    | StoryblokSimplePage
    | StoryblokTestimonial
    | StoryblokTestimonialSection
    | StoryblokText
  )[];
  component: "quiz-page-type1";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokSimplePage {
  body?: (
    | StoryblokBanner
    | StoryblokDropdown
    | StoryblokTest
    | StoryblokButton
    | StoryblokButtonAmadeu
    | StoryblokDatePicker
    | StoryblokEmailInput
    | StoryblokFooter
    | StoryblokHero
    | StoryblokNavbar
    | StoryblokNumberInput
    | StoryblokPageTestAmadeu
    | StoryblokPage
    | StoryblokQuizPageType1
    | StoryblokSimplePage
    | StoryblokTestimonial
    | StoryblokTestimonialSection
    | StoryblokText
  )[];
  component: "simple-page";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokTestimonial {
  author?: string;
  body?: StoryblokRichtext;
  component: "testimonial";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokTestimonialSection {
  heading?: string;
  subheading?: string;
  testimonials?: (ISbStoryData<StoryblokTestimonial> | string)[];
  component: "testimonialSection";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokText {
  content?: string;
  component: "text";
  _uid: string;
  [k: string]: unknown;
}
